[project]
name = "circular_deps"
version = "0.1.0"
description = "CMake circular dependency experiments with reproducible toolchain"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "win-64"]

[dependencies]
cmake = ">=3.28,<4.0"
ninja = "*"

[target.linux-64.dependencies]
clang = ">=17.0.0"
lld = "*"
gcc = "*"
gxx = "*"

[target.osx-64.dependencies]
clang = "*"

[target.win-64.dependencies]
llvm-tools = "*"
